---
title: "logistic_1113"
author: "심현구"
date: "2023-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd('C:/Users/mrg07/Desktop')
library(tidyverse)
```

# 찐최종.csv로 로지스틱으로 파생변수 유의성 확인

```{r}
# year 유의성 확인: p-value = 0.47
df <- read.csv('찐최종.csv', header = T)
df <- df %>% 
  filter(complete.cases(.)) %>% 
  select(-c(length, fuckyou, emotion_기쁨, emotion_당황, emotion_분노,
            emotion_불안, emotion_불안, emotion_상처, emotion_슬픔))
logit <- glm(data = df, formula = label~., family = 'binomial')
summary <- summary(logit)
tail(summary$coefficients, 1)
```

```{r}
# length 유의성 확인: p-value = 0.53
df <- read.csv('찐최종.csv', header = T)
df <- df %>% 
  filter(complete.cases(.)) %>% 
  select(-c(year, fuckyou, emotion_기쁨, emotion_당황, emotion_분노,
            emotion_불안, emotion_불안, emotion_상처, emotion_슬픔))
logit <- glm(data = df, formula = label~., family = 'binomial')
summary <- summary(logit)
tail(summary$coefficients, 1)
```


```{r}
# fuckyou 유의성 확인: p-value = 0.99
df <- read.csv('찐최종.csv', header = T)
df <- df %>% 
  filter(complete.cases(.)) %>% 
  select(-c(year, length, emotion_기쁨, emotion_당황, emotion_분노,
            emotion_불안, emotion_불안, emotion_상처, emotion_슬픔))
logit <- glm(data = df, formula = label~., family = 'binomial')
summary <- summary(logit)
tail(summary$coefficients, 1)
```

```{r}
# emotions 유의성 확인: p-value = 0.99
df <- read.csv('찐최종.csv', header = T)
df <- df %>% 
  filter(complete.cases(.)) %>% 
  select(-c(year, length, fuckyou))
logit <- glm(data = df, formula = label~., family = 'binomial')
summary <- summary(logit)
tail(summary$coefficients, 6)
```


```{r}
# 상관관계 확인

df <- read.csv('찐최종.csv', header = T)
df <- df %>% 
  filter(complete.cases(.))
cor(df$year, df$length)   # -0.15 상관관계 거의 없음!
cor(df$year, df$fuckyou)   # -0.26 상관관계 거의 없음!
cor(df$length, df$fuckyou)   # 0.18 상관관계 거의 없음!
```






# kiwi_ft_1113.csv로 로지스틱으로 파생변수 유의성 확인

```{r}
df <- read.csv('kiwi_ft_1113.csv', header = T)
asdf <- read.csv('찐최종.csv', header = T)
year <- asdf$year
length <- asdf$length
fuckyou <- asdf$fuckyou

df <- cbind(df, length)
```

```{r}
# year 유의성 확인: p-value == 0
df <- read.csv('kiwi_ft_1113.csv', header = T)
asdf <- read.csv('찐최종.csv', header = T)
year <- asdf$year
length <- asdf$length
fuckyou <- asdf$fuckyou

df <- cbind(df, length)

df <- df %>% 
  filter(complete.cases(.)) %>% 
  select(-c(length, fuckyou))
logit <- glm(data = df, formula = label~., family = 'binomial')
summary <- summary(logit)
tail(summary$coefficients, 1)
```
```{r}
# length 유의성 확인: p-value = 0.
df <- read.csv('kiwi_ft_1113.csv', header = T)
asdf <- read.csv('찐최종.csv', header = T)
year <- asdf$year
length <- asdf$length
fuckyou <- asdf$fuckyou

df <- cbind(df, length)

df <- df %>% 
  filter(complete.cases(.)) %>% 
  select(-c(year, fuckyou))
logit <- glm(data = df, formula = label~., family = 'binomial')
summary <- summary(logit)
tail(summary$coefficients, 1)
```

```{r}
# fuckyou 유의성 확인: p-value = 0.
df <- read.csv('kiwi_ft_1113.csv', header = T)
asdf <- read.csv('찐최종.csv', header = T)
year <- asdf$year
length <- asdf$length
fuckyou <- asdf$fuckyou

df <- cbind(df, length)
df <- df %>% 
  filter(complete.cases(.)) %>% 
  select(-c(length, year))
logit <- glm(data = df, formula = label~., family = 'binomial')
summary <- summary(logit)
tail(summary$coefficients, 1)
```



